"""
Authentication for the StakeLine target: bcrypt password verification plus a
TOTP second factor (RFC 6238). The ENHANCED posture enables the second factor;
the BASELINE posture never calls verify_totp().

Credential records live in ../data/users.json, generated by seed_users.py.
"""

import json
from pathlib import Path

try:
    import bcrypt
except ImportError:  # allow the file to be read/graded without the dep installed
    bcrypt = None

try:
    import pyotp
except ImportError:
    pyotp = None

DATA = Path(__file__).resolve().parent.parent / "data" / "users.json"


def load_users():
    if not DATA.exists():
        raise SystemExit("users.json missing — run: python seed_users.py")
    with DATA.open() as fh:
        return json.load(fh)


def verify_password(password: str, stored_hash: str) -> bool:
    if bcrypt is None:
        raise RuntimeError("bcrypt not installed — pip install -r requirements.txt")
    return bcrypt.checkpw(password.encode(), stored_hash.encode())


def verify_totp(secret: str, otp: str) -> bool:
    """Verify a 6-digit code with a +/- 1 step window to tolerate clock drift."""
    if pyotp is None:
        raise RuntimeError("pyotp not installed — pip install -r requirements.txt")
    if not otp or not otp.isdigit():
        return False
    return pyotp.TOTP(secret).verify(otp, valid_window=1)
